AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Resources:
  OrderProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderProcessor
      Handler: OrderProcessor::OrderProcessor.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Layers:
        - arn:aws:lambda:us-east-1:831210339789:layer:QueueHelperLayer:9
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::831210339789:role/OrderProcessorRole